version: '3'

services:
  haproxy:
    build:
      context: ../
      dockerfile: ./deployment/haproxy/Dockerfile
    container_name: lab10_haproxy
    depends_on:
      pgsql01:
        condition: service_healthy
      pgsql02:
        condition: service_healthy
      pgsql03:
        condition: service_healthy
    restart: always
    networks:
      - local
    ports:
      - "5433:5432"
      - "8404:8404"



  pgsql01:
    build:
      context: ../
      dockerfile: ./deployment/pgsql/Dockerfile
    container_name: lab10_pgsql01
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 15
#    environment:
#      - PGPORT=5432
    networks:
      - local

  pgsql02:
    build:
      context: ../
      dockerfile: ./deployment/pgsql/Dockerfile
    container_name: lab10_pgsql02
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 15
#    environment:
#      - PGPORT=5432
    networks:
      - local

  pgsql03:
    build:
      context: ../
      dockerfile: ./deployment/pgsql/Dockerfile
    container_name: lab10_pgsql03
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 15
    networks:
      - local



  loaderapp:
    build:
      context: ../
      dockerfile: ./deployment/loader/Dockerfile
    container_name: lab10_loader
    depends_on:
      pgsql01:
        condition: service_healthy
      pgsql02:
        condition: service_healthy
      pgsql03:
        condition: service_healthy
    restart: always
    tty: true
    stdin_open: true
    networks:
      - local

networks:
  local: